<?xml version="1.0" encoding="UTF-8"?>
<ActionCollection version="2" name="Krita">
  <Actions category="Krita">
     <text>PDF Notebook</text>

     <Action name="pdfio_open_notebook">
       <icon></icon>
       <text>Open PDF as notebook</text>
       <whatsThis></whatsThis>
       <toolTip></toolTip>
       <iconText></iconText>
       <activationFlags>10000</activationFlags>
       <activationConditions>0</activationConditions>
       <shortcut></shortcut>
       <isCheckable>false</isCheckable>
       <statusTip></statusTip>
     </Action>

     <Action name="pdfio_save_page">
       <icon></icon>
       <text>Save the page notes</text>
       <whatsThis></whatsThis>
       <toolTip></toolTip>
       <iconText></iconText>
       <activationFlags>10000</activationFlags>
       <activationConditions>0</activationConditions>
       <shortcut></shortcut>
       <isCheckable>false</isCheckable>
       <statusTip></statusTip>
     </Action>

     <Action name="pdfio_next_page">
       <icon></icon>
       <text>Next page</text>
       <whatsThis></whatsThis>
       <toolTip></toolTip>
       <iconText></iconText>
       <activationFlags>10000</activationFlags>
       <activationConditions>0</activationConditions>
       <shortcut>PgDown</shortcut>
       <isCheckable>false</isCheckable>
       <statusTip></statusTip>
     </Action>

     <Action name="pdfio_previous_page">
       <icon></icon>
       <text>Previous page</text>
       <whatsThis></whatsThis>
       <toolTip></toolTip>
       <iconText></iconText>
       <activationFlags>10000</activationFlags>
       <activationConditions>0</activationConditions>
       <shortcut>PgUp</shortcut>
       <isCheckable>false</isCheckable>
       <statusTip></statusTip>
     </Action>
  </Actions>
</ActionCollection>
